### ISSUE TITLE
Modelo conceitual ou lógico: Ordenar as colunas de forma a gerar um script mais organizado do banco.

### ISSUE THREAD

**Issue by isdabesteira** [isdabesteira/git-01#17]
No modelo conceitual ou lógico devemos ter a seguinte sequência:
1. nome,
1.  sexo, 
1. idade, 
1. endereço, 
1. telefone, 
1. valor pago pelo curso, 
1. data de inscrição do curso

**Comment by isdabesteira** [comment]
Acho que devíamos alterar o ítem 7 com 6.

**Comment by padreperereca** [comment]
Modificar a sequência de colunas ou atributos.

**Comment by padreperereca** [comment]
Talvez seja melhor modificar a sequência de atributos, pois os outros estão sendo gerados direta ou indiretamente pelo modelo conceitual.

**Comment by isdabesteira** [comment]
Melhor não fazer essa issue, pois ele irá gerar um retrabalho grande visto que o modelo está em sua fase inicial e o código é gerado em cascata. Assim ao modificarmos a sequência de atributos vamos gerar trabalho desnecessário. Fechar e regeitar o issue.
